#!/bin/sh -xu

# $2: Full path to the installation destination.
# For example: /Applications

mkdir -p "/usr/local/bin"
ln -sf "$2/FileBot.app/Contents/MacOS/filebot.sh" "/usr/local/bin/filebot"

exit 0
